import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import GlobalStyles from '@/styles/themes/globalStyles'
import Providers from '@/lib/provider'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <GlobalStyles />
          {props.children}
        </Providers>
      </body>
    </html>
  )
}
